CREATE TABLE IF NOT EXISTS { { fiscal_period } } (
    `fiscal_period_id` INT(11) NOT NULL AUTO_INCREMENT,
    `description` longtext DEFAULT '' COMMENT 'description for the fiscal period',
    `code` VARCHAR(255) DEFAULT '' COMMENT 'code for the fiscal period',
    `start_date` date DEFAULT NULL COMMENT 'start date of the event',
    `end_date` date DEFAULT NULL COMMENT 'end date of the event',
    `status` TINYINT(1) DEFAULT '1' COMMENT 'is the fiscal period currently active',
    `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'time of the last update to the fiscal period',
    `owner_id` INT(11) DEFAULT NULL COMMENT 'owner of the fiscal period',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the fiscal period is visible to',
    PRIMARY KEY (`fiscal_period_id`),
    FOREIGN KEY (`owner_id`) REFERENCES `borrowers` (`borrowernumber`)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS { { ledgers } } (
    `ledger_id` INT(11) NOT NULL AUTO_INCREMENT,
    `fiscal_period_id` INT(11) DEFAULT NULL COMMENT 'fiscal period the ledger applies to',
    `name` VARCHAR(255) DEFAULT '' COMMENT 'name for the ledger',
    `description` longtext DEFAULT '' COMMENT 'description for the ledger',
    `code` VARCHAR(255) DEFAULT '' COMMENT 'code for the ledger',
    `external_id` VARCHAR(255) DEFAULT '' COMMENT 'external id for the ledger for use with external accounting systems',
    `currency` VARCHAR(10) DEFAULT '' COMMENT 'currency of the ledger',
    `status` TINYINT(1) DEFAULT '1' COMMENT 'is the ledger currently active',
    `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'time of the last update to the ledger',
    `owner_id` INT(11) DEFAULT NULL COMMENT 'owner of the ledger',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the ledger is visible to',
    `ledger_value` decimal(28,6) DEFAULT 0.000000 COMMENT 'value of the ledger',
    `over_spend_allowed` TINYINT(1) DEFAULT '1' COMMENT 'is an overspend allowed on the ledger',
    `over_encumbrance_allowed` TINYINT(1) DEFAULT '1' COMMENT 'is an overencumbrance allowed on the ledger',
    `oe_warning_percent` decimal(5,4) DEFAULT 0.0000 COMMENT 'percentage limit for overencumbrance',
    `oe_limit_amount` decimal(28,6) DEFAULT 0.000000 COMMENT 'limit for overspend',
    `os_warning_sum` decimal(28,6) DEFAULT 0.000000 COMMENT 'amount to trigger a warning for overspend',
    `os_limit_sum` decimal(28,6) DEFAULT 0.000000 COMMENT 'amount to trigger a block on the ledger for overspend',
    PRIMARY KEY (`ledger_id`),
    FOREIGN KEY (`fiscal_period_id`) REFERENCES { { fiscal_period } } (`fiscal_period_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`owner_id`) REFERENCES `borrowers` (`borrowernumber`)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS { { fund_group } } (
    `fund_group_id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) DEFAULT '' COMMENT 'name for the fund group',
    `currency` VARCHAR(10) DEFAULT '' COMMENT 'currency of the fund allocation',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the fund allocation is visible to',
    PRIMARY KEY (`fund_group_id`)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS { { funds } } (
    `fund_id` INT(11) NOT NULL AUTO_INCREMENT,
    `ledger_id` INT(11) DEFAULT NULL COMMENT 'ledger the fund applies to',
    `fiscal_period_id` INT(11) DEFAULT NULL COMMENT 'fiscal period the fund applies to',
    `name` VARCHAR(255) DEFAULT '' COMMENT 'name for the fund',
    `description` longtext DEFAULT '' COMMENT 'description for the fund',
    `fund_type` VARCHAR(255) DEFAULT '' COMMENT 'type for the fund',
    `fund_group_id` INT(11) DEFAULT NULL COMMENT 'group for the fund',
    `code` VARCHAR(255) DEFAULT '' COMMENT 'code for the fund',
    `external_id` VARCHAR(255) DEFAULT '' COMMENT 'external id for the fund for use with external accounting systems',
    `currency` VARCHAR(10) DEFAULT '' COMMENT 'currency of the fund',
    `status` TINYINT(1) DEFAULT '1' COMMENT 'is the fund currently active',
    `owner_id` INT(11) DEFAULT NULL COMMENT 'owner of the fund',
    `fund_value` decimal(28,6) DEFAULT 0.000000 COMMENT 'value of the fund',
    `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'time of the last update to the fund',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the fund is visible to',
    PRIMARY KEY (`fund_id`),
    FOREIGN KEY (`ledger_id`) REFERENCES { { ledgers } } (`ledger_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`fiscal_period_id`) REFERENCES { { fiscal_period } } (`fiscal_period_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`fund_group_id`) REFERENCES { { fund_group } } (`fund_group_id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`owner_id`) REFERENCES `borrowers` (`borrowernumber`)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS { { sub_funds } } (
    `sub_fund_id` INT(11) NOT NULL AUTO_INCREMENT,
    `fund_id` INT(11) DEFAULT NULL COMMENT 'parent fund for the sub fund',
    `ledger_id` INT(11) DEFAULT NULL COMMENT 'ledger the sub_fund applies to',
    `fiscal_period_id` INT(11) DEFAULT NULL COMMENT 'fiscal period the sub_fund applies to',
    `name` VARCHAR(255) DEFAULT '' COMMENT 'name for the sub_fund',
    `description` longtext DEFAULT '' COMMENT 'description for the sub_fund',
    `sub_fund_type` VARCHAR(255) DEFAULT '' COMMENT 'type for the sub_fund',
    `code` VARCHAR(255) DEFAULT '' COMMENT 'code for the sub_fund',
    `external_id` VARCHAR(255) DEFAULT '' COMMENT 'external id for the sub_fund for use with external accounting systems',
    `currency` VARCHAR(10) DEFAULT '' COMMENT 'currency of the sub_fund',
    `status` TINYINT(1) DEFAULT '1' COMMENT 'is the sub_fund currently active',
    `owner_id` INT(11) DEFAULT NULL COMMENT 'owner of the sub_fund',
    `sub_fund_value` decimal(28,6) DEFAULT 0.000000 COMMENT 'value of the sub_fund',
    `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'time of the last update to the sub_fund',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the sub_fund is visible to',
    PRIMARY KEY (`sub_fund_id`),
    FOREIGN KEY (`fund_id`) REFERENCES { { funds } } (`fund_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ledger_id`) REFERENCES { { ledgers } } (`ledger_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`fiscal_period_id`) REFERENCES { { fiscal_period } } (`fiscal_period_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`owner_id`) REFERENCES `borrowers` (`borrowernumber`)
) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS { { fund_allocation } } (
    `fund_allocation_id` INT(11) NOT NULL AUTO_INCREMENT,
    `fund_id` INT(11) DEFAULT NULL COMMENT 'fund the fund allocation applies to',
    `sub_fund_id` INT(11) DEFAULT NULL COMMENT 'sub fund the fund allocation applies to',
    `ledger_id` INT(11) DEFAULT NULL COMMENT 'ledger the fund allocation applies to',
    `fiscal_period_id` INT(11) DEFAULT NULL COMMENT 'fiscal period the fund allocation applies to',
    `allocation_amount` decimal(28,6) DEFAULT 0.000000 COMMENT 'amount for the allocation',
    `reference` VARCHAR(255) DEFAULT '' COMMENT 'allocation reference',
    `note` longtext DEFAULT '' COMMENT 'any notes associated to the allocation',
    `currency` VARCHAR(10) DEFAULT '' COMMENT 'currency of the fund allocation',
    `owner_id` INT(11) DEFAULT NULL COMMENT 'owner of the fund allocation',
    `is_transfer` TINYINT(1) DEFAULT '0' COMMENT 'is the fund allocation a transfer to/from another fund',
    `last_updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'time of the last update to the fund allocation',
    `visible_to` VARCHAR(255) DEFAULT '' COMMENT 'library groups the fund allocation is visible to',
    PRIMARY KEY (`fund_allocation_id`),
    FOREIGN KEY (`sub_fund_id`) REFERENCES { { sub_funds } } (`sub_fund_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`fund_id`) REFERENCES { { funds } } (`fund_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`ledger_id`) REFERENCES { { ledgers } } (`ledger_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`fiscal_period_id`) REFERENCES { { fiscal_period } } (`fiscal_period_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`owner_id`) REFERENCES `borrowers` (`borrowernumber`)
) ENGINE = INNODB;